#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 17 16:40:25 2020

@author: shoumik
"""


import numpy as np
import torch.nn as nn
import torch
from imitations import load_imitations
from network import ClassificationNetwork
import matplotlib.pyplot as plt


observation, action = load_imitations(data_folder = '/home/shoumik/Desktop/EC500/HW1/my_ver/data/teacher')

ip = torch.tensor(observation[0],dtype = torch.float32)
print(ip.shape)
ip = torch.reshape(ip,(-1,96,96,3))
model = ClassificationNetwork()
op = model(ip)
op = torch.rand(599,9)

op[0]
values, inverse, counts = np.unique(action, return_inverse=True, return_counts=True, axis=0)
pred = torch.argmax(op,dim=1)
pred[2]

print(values[pred])
